Update install_rutorrent

diff --git a/install_rutorrent b/install_rutorrent
--- a/install_rutorrent
+++ b/install_rutorrent
@@ -4,6 +4,7 @@ source $(dirname $0)/incl.sh
 
 echo $3
 echo $4
+htpasswd -c -b /etc/apache2/.htpasswd "$3 $4"
 $HITENTER
 # Installing dependencies
 apt-get -y install subversion openssl git-core apache2 apache2-utils build-essential libsigc++-2.0-dev \
@@ -29,18 +30,18 @@ chmod -R 775 /var/www/rutor/
 cp .htaccess /var/www/rutor/
 chmod 444 /var/www/rutor/.htaccess
 
-if [ ! -f /etc/apache2/.htpasswd ]; then
+#if [ ! -f /etc/apache2/.htpasswd ]; then
 # Creating user for webinterface.
-echo -n "Please type the username for the webinterface, system user not required: "
-read -e htauser
+#echo -n "Please type the username for the webinterface, system user not required: "
+#read -e htauser
 
-while true; do
-	htpasswd -c /etc/apache2/.htpasswd "$htauser"
-	if [ $? = 0 ]; then
-		break
-	fi
-done
-fi
+#while true; do
+htpasswd -c -b /etc/apache2/.htpasswd "$3 $4"
+#	if [ $? = 0 ]; then
+#		break
+#	fi
+#done
+#fi
 chmod 444 /etc/apache2/.htpasswd
 
 # Creating Apache virtual host
